services:
  fastapi:
    build: ./fast_api
    container_name: fastapi_app
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - APP_HOST=${APP_HOST}
      - APP_PORT=${APP_PORT}
      - PYTHONPATH=/code
      - EDF_HOST_PATH=${EDF_HOST_PATH}
      - EDF_CONTAINER_PATH=${EDF_CONTAINER_PATH}
    depends_on:
      db_fastapi:
        condition: service_healthy
    volumes:
      - ./fast_api:/code
      - ${EDF_HOST_PATH}:${EDF_CONTAINER_PATH}:ro  # montagem s√≥ leitura
    working_dir: /code
    command: sh -c "alembic upgrade head && uvicorn app.main:app --host ${APP_HOST} --port ${APP_PORT} --reload"

  db_fastapi:
    image: postgres:15
    container_name: postgres_fastapi
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_fastapi_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_fastapi_data:
